### PR TITLE
Fix some typos and spelling mistakes

### PR DESCRIPTION
**Pull request by garwil**
Re: The Reddit comment linked below. I've started to correct some of the typos and spelling errors in the file. I might do some more later if there's any interest.

I wonder whether there's a need to curate some of the quotes though? There's multiple languages, and lots don't seem to fit the theme of the application.

[https://www.reddit.com/r/commandline/comments/og4dzv/wisdom_tree_a_command_line_concentration_app/h4gytwp?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/commandline/comments/og4dzv/wisdom_tree_a_command_line_concentration_app/h4gytwp?utm_source=share&utm_medium=web2x&context=3)

### CODE REVIEW

**Comment by Esamanoaz** [comment]
> I wonder whether there's a need to curate some of the quotes though? There's multiple languages, and lots don't seem to fit the theme of the application.

I agree. Checkout this line: `Those sweet lips. My, oh my, I could kiss those lips all night long. Good things come to those who wait.` The last sentence there could be inspirational. The first two are completely unrelated to the last and don't fit the inspiring/motivating/wise theme.

**Comment by shivanshu-semwal** [comment]
there is a typo in the `README.md` too

image

**Comment by HACKER097** [comment]
> there is a typo in the `README.md` too
> 
> image

Not a typo, `main.py` is now in `wisdom-tree/wisdom_tree/main.py`

**Comment by HACKER097** [comment]
> Re: The Reddit comment linked below. I've started to correct some of the typos and spelling errors in the file. I might do some more later if there's any interest.
> 
> I wonder whether there's a need to curate some of the quotes though? There's multiple languages, and lots don't seem to fit the theme of the application.
> 
> https://www.reddit.com/r/commandline/comments/og4dzv/wisdom_tree_a_command_line_concentration_app/h4gytwp?utm_source=share&utm_medium=web2x&context=3

Ok, this is a big issue, and cannot be done manually. I've removed all lines with non-English characters using perl, any ideas how we can get rid of typos? Maybe aspell could help.

**Comment by Esamanoaz** [comment]
Most of the errors are punctuation errors. I can think of an idea for a python script that would go through character by character and solve that.

As for spelling errors, somebody could run a spellchecker like Grammarly through the file, or the Microsoft Word spell check.

I'll try to get on that today.

**Comment by Esamanoaz** [comment]
> Not a typo, `main.py` is now in `wisdom-tree/wisdom_tree/main.py`

I think shivanshu-semwal means that in the screenshot it is spelled wisdom**e** with an e at the end.
Also, I will be sending a pull request soon. I wrote a script to edit the punctuation of the quotes.

**Comment by Benjiko99** [comment]
Very inspirational quote :laughing: _"It is the destiny of the weak to be devoured by the strong."_

**Comment by HACKER097** [comment]
> > Not a typo, `main.py` is now in `wisdom-tree/wisdom_tree/main.py`
> 
> I think shivanshu-semwal means that in the screenshot it is spelled wisdom**e** with an e at the end.
> Also, I will be sending a pull request soon. I wrote a script to edit the punctuation of the quotes.

aah, didnt see that, it has now been fixed

**Comment by HACKER097** [comment]
> Very inspirational quote laughing _"It is the destiny of the weak to be devoured by the strong."_

Maybe time to get a new quote list? When I first made this one, I went with quantity over quality and scraped quotes from websites without reading them. With that said, here are a few of my favorites:-

*Guys willing to hold your dick are a dime a dozen*
*Being born is like being kidnapped. And then sold into slavery.*
*Kill me, or you are a murderer.*
*You fuck - you ate my cat!*
*A girl always remembers the first corpse she shaves.*

**Comment by HACKER097** [comment]
Closing this.

**Pull request closed without merging**
