### PR TITLE
Fix for treedata overriding

### PR DESCRIPTION
**Pull request by JacobGL0226**
Resolves [the treedata overriding issue](https://github.com/HACKER097/wisdom-tree/issues/21).

Essentially, it was caused by [line 4 in MANIFEST.in](https://github.com/HACKER097/wisdom-tree/blob/main/MANIFEST.in#L4).

**graft** includes all files in a given directory, which in our case would also be **res/treedata**. 

Because it is assumed that all files included in the package are important, and should be overridden when updated, it will assume that **treedata** is a depreciated file that should be overridden with whatever new **treedata** file is included in the newest package.

All that is needed to fix this is to exclude the treedata file after grafting the **res** directory.

### CODE REVIEW

**Comment by JacobGL0226** [comment]
I should also note, make sure you remove your **build/** (and maybe **dist/**?) directories before packaging the project. If you leave these directories, it can cause **treedata** to be added regardless because it is found in them despite being removed from the package.

**Comment by HACKER097** [comment]
> I should also note, make sure you remove your **build/** (and maybe **dist/**?) directories before packaging the project. If you leave these directories, it can cause **treedata** to be added regardless because it is found in them despite being removed from the package.

This is embarrassing, but I have no idea how pypi works. Another contributor turned the project into a package, and I've using these commands to update it.
`python3 setup.py sdist bdist_wheel`
`twine upload --verbose --skip-existing dist/wisdom-tree*`
What do i need to change here?

**Comment by JacobGL0226** [comment]
> This is embarrassing, but I have no idea how pypi works. Another contributor turned the project into a package, and I've using these commands to update it.
> `python3 setup.py sdist bdist_wheel`
> `twine upload --verbose --skip-existing dist/wisdom-tree*`
> What do i need to change here?

You would need to change:
twine upload --verbose --skip-existing dist/wisdom-tree*
to:
twine upload --verbose --skip-existing dist/wisdom-tree-0.1.1*

An asterisk acts as a wildcard, and replaces itself with every possible file starting with whatever is written prior to it. You would not want to upload every version of wisdom-tree, just the newest version.

The main issue had to do with the **MANIFEST.in** file, which determines which files are included into your package. I modified that file such that it ignores the **treedata** file, and so most of what needs to be done now is to merge my changes, and then with those new changes, packaging the project should ignore **treedata**.

**Comment by HACKER097** [comment]
aight, I just updated, but the age still got reset. I assume this takes effect from the next updates?

**Comment by JacobGL0226** [comment]
> aight, I just updated, but the age still got reset. I assume this takes effect from the next updates?

Would you mind running the upgrade command and showing me your output? It does not seem to override when upgrading on my end.

**Comment by HACKER097** [comment]
> > aight, I just updated, but the age still got reset. I assume this takes effect from the next updates?
> 
> Would you mind running the upgrade command and showing me your output? It does not seem to override when upgrading on my end.

https://imgur.com/FcZ71h9.png

**Comment by JacobGL0226** [comment]
> https://imgur.com/FcZ71h9.png

That's pretty odd, it doesn't seem to overwrite for me. I imagine it might have to do with it seeming to find wisdom-tree-0.1.0 on your system, it definitely should not be picking up on older versions before the fix for treedata. Try running **pip3 uninstall wisdom-tree** and giving it a reinstall to see if it still happens. 

For new installs, I found the easiest way to test if it saves treedata is to temporarily change the growth rate to something really quick, save the treedata, and then reinstalling wisdom-tree to see if the age is still there after reinstalling. 

While reinstalling, pay attention to see if it says anything about any versions before 0.1.1, because those were the problematic versions that would override treedata.

**Comment by HACKER097** [comment]
Yes, re-installing does not reset the age. Uninstalling 0.1.0 also removed the treedata file, so a new one with age 1 is created when i ran 0.1.2, shouldn't be a problem from next updates.

**Pull request merged**
