### PR TITLE
Converting to a pip installable app

### PR DESCRIPTION
**Pull request by yasserfarouk**
1- Added setup.py allowing creation of a package using

`python setup.py sdist bdist_wheel`

2. Adding pypi support. You can now upload this to pypi as a package
   using:
`pip install twine`
`twine upload dist/wisdomtree-0.0.1*`

After that, users can just do:
`pip isntall wisdomtree`

You can check `setup.py` to confirm that the information provided for the author and github are for the original author of the wisdom-tree (HACKER097).

3. Adding an entry point called `wisdomtree`. After installation using
   pip, users can just do:

  `wisdom`

  from anywahere to run the app.

4. Refactoring timer constants on the top of the file to make it easy to add custom values.
5. Moving main.py and all files to within wisdomtree as recommended for python project structure.
6. Adding vim key support (See the README)

### CODE REVIEW

**Comment by HACKER097** [comment]
This is amazing! Just replace `wisdomtree` with `wisdom-tree` everywhere, and I'll pull it in.

**Comment by yasserfarouk** [comment]
I am not sure about windows though. I only use mac and Linux and we can have an app called `wisdom-tree` there. Can we have that on windows?
Anyway, will do the updates now.

thanks

**Comment by yasserfarouk** [comment]
I did the change to wisdom-tree
Please check it f3db04217ea41e100d6c643dc4579dff0b3833a1

**Comment by yasserfarouk** [comment]
Please note that I did not push to pypi because it should be pushed under your name.

You will need to use twine:

`pip install twine`
`python setup.py sdist bdist_wheel`
`twine upload dist/wisdom-tree*`

It will ask for your username and password at [pypi](https://pypi.org/).

After that, we can all just pip install wisdom-tree :-)

**Comment by HACKER097** [comment]
Its here! `pip install wisdom-tree` will install wisdom tree!

**Pull request merged**
